const plyers = [
    {
    id: 1,
    name: "Erling Haaland",
    nationality: "Norway",
    team: "Manchester City",
    jerseynumber: 9,
    position: "Attack Centre Forward",
    rating: 88,
    image: "https://i.guim.co.uk/img/media/738ce55b0210242ed89525dc7217389fcdd954f6/867_295_3097_1858/master/3097.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=93c023f0b3182e74b5320381712d32d3",
    },
    {
    id: 2,
    name: "Kylian Mbappé",
    nationality: "France",
    team: "Paris Saint-Germain",
    jerseynumber: 10,
    position: "Forward",
    rating: 91,
    image: "https://www.cessnockadvertiser.com.au/images/transform/v1/crop/frm/silverstone-feed-data/37aa46be-d336-4ecb-8253-ff7677a4d67d.jpg/r0_0_800_600_w800_h600_fmax.jpg",
    },
    {
    id: 3,
    name: "Vinícius Jr",
    nationality: "Brazil",
    team: "Real Madrid",
    jerseynumber: 20,
    position: "Attacking Midfielder",
    rating: 88,
    image: "https://media.cnn.com/api/v1/images/stellar/prod/230615113836-vinicius-jr-real-madrid-file-restricted-060423.jpg?c=original",
    },
    {
    id: 4,
    name: "Raheem Sterling",
    nationality: "England",
    team: "Chelsea",
    jerseynumber: 17,
    position: "Right Winger: Centre-Forward",
    rating: 85,
    image: "https://img.allfootballapp.com/www/M00/3D/50/720x-/-/-/CgAGVWP_YAOAD6xlAADDwQxRQGg205.jpg.webp",
    },
    {
    id: 5,
    name: "Luis Díaz",
    nationality: "Colombia",
    team: "Liverpool",
    jerseynumber: 23,
    position: "Right Winger",
    rating: 84,
    image: "https://sky.shorthandstories.com/inside-the-rise-of-luis-diaz/assets/XiFAxvm9TQ/diaz-portrait-2985x2945.jpeg",
    },
    {
    id: 6,
    name: "Raphinha",
    nationality:"Brazil",
    team: "FC Barcelona",
    jerseynumber: 22,
    position: "Right Winger",
    rating:84,
    image: "https://s.hs-data.com/bilder/spieler/gross/346550.jpg",
    },
]
export default players;
